package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Buildcnf'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Buildcnf")) {
    expectSteps {
        step {
            type = "Metarunner_Mr"
            executionMode = BuildStep.ExecutionMode.DEFAULT
            param("githubtokenroot", "credentialsJSON:4b7d9c29-fd7e-47df-b48f-c2bae8c224d2")
        }
    }
    steps {
        insert(1) {
            script {
                scriptContent = "n"
            }
        }
    }
}
