package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'FromMR'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("FromMR")) {
    expectSteps {
        step {
            type = "Metarunner0_BaseMR0"
            executionMode = BuildStep.ExecutionMode.DEFAULT
        }
    }
    steps {
        update<BuildStep>(0) {
            clearConditions()
            param("defPar1", "3")
        }
    }
}
